# Generated by Django 5.2.5 on 2025-11-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
