# Generated by Django 5.2.5 on 2025-11-28 14:47

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matricula',
            field=models.CharField(default=builtins.print, max_length=16),
            preserve_default=False,
        ),
    ]
