# Generated by Django 5.2.1 on 2025-06-03 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_alternativa_correta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostaaluno',
            name='aluno',
        ),
        migrations.AddField(
            model_name='respostaaluno',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas_aluno', to=settings.AUTH_USER_MODEL),
        ),
    ]
