# Generated by Django 5.2.5 on 2025-11-29 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField(max_length=100)),
                ('conquistado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmblemaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser')),
                ('emblema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emblema')),
            ],
        ),
    ]
