# Generated by Django 5.2.5 on 2025-11-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quiz_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='tipo_questoes',
            field=models.CharField(choices=[('Múltipla Escolha', 'Múltipla Escolha'), ('Verdadeiro ou Falso', 'Verdadeiro ou Falso')], default='Múltipla Escolha', max_length=20),
        ),
    ]
