# Generated by Django 5.2.5 on 2025-11-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emblema_emblemauser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emblema',
            name='conquistado',
        ),
        migrations.AddField(
            model_name='emblema',
            name='conquistado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emblemauser',
            name='logo',
            field=models.ImageField(null=True, upload_to='emblemas/'),
        ),
    ]
