# Generated by Django 5.2.5 on 2025-11-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_quiz_tipo_questoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='tipo_questoes',
            field=models.CharField(choices=[('Múltipla Escolha', 'Múltipla Escolha'), ('Verdadeiro ou Falso', 'Verdadeiro ou Falso'), ('Múltipla Escolha e Verdadeiro ou Falso', 'Múltipla Escolha e Verdadeiro ou Falso')], default='Múltipla Escolha', max_length=38),
        ),
    ]
