# Generated by Django 5.2.5 on 2025-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_emblema_conquistado_emblema_conquistado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emblemauser',
            name='logo',
        ),
        migrations.AddField(
            model_name='emblema',
            name='logo',
            field=models.ImageField(null=True, upload_to='emblemas/'),
        ),
    ]
