# Generated by Django 5.2.5 on 2025-11-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_emblemauser_logo_emblema_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emblema',
            name='conquistado_em',
        ),
        migrations.AddField(
            model_name='emblemauser',
            name='conquistado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
