# Generated by Django 5.2.5 on 2025-11-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_emblema_conquistado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='percentual_acertos',
        ),
    ]
