# Generated by Django 5.2.5 on 2025-11-30 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_certificado_percentual_acertos'),
    ]

    operations = [
        migrations.AddField(
            model_name='emblema',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.disciplina'),
        ),
    ]
