# Generated by Django 5.2.1 on 2025-06-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='api.questao'),
        ),
    ]
