# Generated by Django 5.2.5 on 2025-11-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_emblema_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='emblema',
            name='nivel',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], max_length=13, null=True),
        ),
    ]
