# Generated by Django 5.2.1 on 2025-06-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_resposta_questao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='alternativa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.alternativa'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='questao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='api.questao'),
        ),
    ]
