# Generated by Django 5.2.5 on 2025-11-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_emblema_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentativa',
            name='status_quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='status_quiz',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('Desistido', 'Desistido'), ('Concluído', 'Concluído')], default='Iniciado', max_length=9),
        ),
    ]
