# Generated by Django 5.2.1 on 2025-06-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_resposta_alternativa_alter_resposta_questao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='explicacao',
        ),
    ]
