# Generated by Django 5.2.5 on 2025-12-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_quiz_status_quiz_tentativa_status_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativa',
            name='disciplna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.disciplina'),
        ),
    ]
