# Generated by Django 5.2.1 on 2025-06-07 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_certificado_percentual_acertos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaaluno',
            name='tentativa',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='alternativa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.alternativa'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='questao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_explicativas', to='api.questao'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='quiz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.quiz'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas_aluno', to=settings.AUTH_USER_MODEL),
        ),
    ]
