# Generated by Django 5.2.5 on 2025-12-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tentativa_disciplna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tentativa',
            old_name='disciplna',
            new_name='disciplina',
        ),
    ]
