# Generated by Django 5.2.5 on 2025-09-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_certificado_usuario_remove_codigo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaaluno',
            name='max_tentativa',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
