# Generated by Django 5.2.5 on 2025-09-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_respostaaluno_max_tentativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='nivel',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], default='Iniciante', max_length=13),
        ),
    ]
