# Generated by Django 5.2.5 on 2025-09-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_desempenho_concluiu_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desempenho',
            name='concluiu_quiz',
        ),
    ]
