# Generated by Django 5.2.5 on 2025-09-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_desempenho_concluiu_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='desempenho',
            name='concluiu_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
