# Generated by Django 5.2.5 on 2025-11-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_emblema_remove_emblemauser_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
