# Generated by Django 5.2.1 on 2025-05-31 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='resposta_correta',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='titulo',
        ),
        migrations.AddField(
            model_name='quiz',
            name='nivel',
            field=models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=13),
        ),
        migrations.CreateModel(
            name='Reposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alternativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='api.questao')),
            ],
        ),
    ]
