# Generated by Django 5.2.1 on 2025-06-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_desempenho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='usuario',
            new_name='aluno',
        ),
    ]
