# Generated by Django 5.2.1 on 2025-05-31 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_certificado_resposta_respostausuario_delete_reposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='api.quiz'),
        ),
    ]
