# Generated by Django 5.2.1 on 2025-05-31 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_questao_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostausuario',
            name='alternativa',
        ),
        migrations.RemoveField(
            model_name='respostausuario',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='respostausuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='resposta',
            name='explicacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alternativa')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_aluno', to='api.aluno')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_explicativas', to='api.questao')),
            ],
        ),
        migrations.DeleteModel(
            name='RespostaExplicacao',
        ),
        migrations.DeleteModel(
            name='RespostaUsuario',
        ),
    ]
