# Generated by Django 5.2.1 on 2025-05-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_respostausuario_alternativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='explicacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
