# Generated by Django 5.2.1 on 2025-05-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alternativa_explicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativa',
            name='explicacao',
        ),
        migrations.AddField(
            model_name='questao',
            name='explicacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
