# Generated by Django 5.2.1 on 2025-06-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_respostaaluno_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='realizando_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
