# Generated by Django 5.2.1 on 2025-06-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_aluno_realizando_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='realizando_quiz',
        ),
    ]
