# Generated by Django 5.2.1 on 2025-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_quiz_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='percentual_acertos',
            field=models.IntegerField(default=0),
        ),
    ]
