# Generated by Django 5.2.2 on 2025-06-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='descricao',
        ),
        migrations.AddField(
            model_name='feedback',
            name='assunto',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='mensagem',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
