# Generated by Django 5.2.2 on 2025-06-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_feedback_descricao_feedback_assunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mensagem',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
