# Generated by Django 5.2.1 on 2025-07-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_feedback_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
            ],
        ),
    ]
