# Generated by Django 5.2.1 on 2025-07-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_emblema'),
    ]

    operations = [
        migrations.AddField(
            model_name='emblema',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='emblemas/'),
        ),
    ]
