# Generated by Django 5.2.5 on 2025-09-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_emblema_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='codigo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='desempenho',
            name='user',
        ),
        migrations.RemoveField(
            model_name='respostaaluno',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='respostaaluno',
            name='user',
        ),
        migrations.AddField(
            model_name='certificado',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aluno'),
        ),
        migrations.AddField(
            model_name='codigo',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aluno'),
        ),
        migrations.AddField(
            model_name='desempenho',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aluno'),
        ),
        migrations.AddField(
            model_name='desempenho',
            name='iniciou_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respostaaluno',
            name='desempenho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.desempenho'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emblema',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='assunto',
            field=models.CharField(default='Feedback sem assunto', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='tentativa',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
            ],
        ),
    ]
