# Generated by Django 5.2.5 on 2025-09-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_quiz_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='desempenho',
            name='concluiu_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
