# Generated by Django 5.2.5 on 2025-09-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_desempenho_concluiu_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desempenho',
            name='iniciou_quiz',
        ),
    ]
