# Generated by Django 5.2.5 on 2025-09-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_desempenho_iniciou_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostaaluno',
            name='max_tentativa',
        ),
        migrations.RemoveField(
            model_name='respostaaluno',
            name='tentativa',
        ),
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('desempenho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.desempenho')),
            ],
        ),
    ]
