# Generated by Django 5.2.5 on 2025-09-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_respostaaluno_max_tentativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativa',
            name='concluiu_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
