# Generated by Django 5.2.5 on 2025-09-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_tentativa_concluiu_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emblema',
            new_name='EmblemaUser',
        ),
    ]
