# Generated by Django 5.2.5 on 2025-09-06 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_emblema_emblemauser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emblemauser',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='emblemauser',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='emblemauser',
            name='nome',
        ),
        migrations.AddField(
            model_name='emblemauser',
            name='emblema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.emblema'),
        ),
    ]
